package fakevac.integrationtests

fun buildThermostatResponse(
    ambientTemperature: Int = 70
): String {
    return StringBuilder("{")
        .append("\"humidity\": 35,")
        .append("\"locale\": \"en-US\",")
        .append("\"temperature_scale\": \"F\",")
        .append("\"is_using_emergency_heat\": false,")
        .append("\"has_fan\": true,")
        .append("\"software_version\": \"5.6.2-3\",")
        .append("\"has_leaf\": false,")
        .append("\"where_id\": \"living-room-id\",")
        .append("\"device_id\": \"thermostat-1-id\",")
        .append("\"name\": \"Living Room (Nest)\",")
        .append("\"can_heat\": true,")
        .append("\"can_cool\": false,")
        .append("\"target_temperature_c\": 20.5,")
        .append("\"target_temperature_f\": 69,")
        .append("\"target_temperature_high_c\": 24.0,")
        .append("\"target_temperature_high_f\": 75,")
        .append("\"target_temperature_low_c\": 20.0,")
        .append("\"target_temperature_low_f\": 68,")
        .append("\"ambient_temperature_c\": 20.5,")
        .append("\"ambient_temperature_f\": $ambientTemperature,")
        .append("\"away_temperature_high_c\": 24.0,")
        .append("\"away_temperature_high_f\": 76,")
        .append("\"away_temperature_low_c]\": 16.5,")
        .append("\"away_temperature_low_f\": 62,")
        .append("\"eco_temperature_high_c\": 24.0,")
        .append("\"eco_temperature_high_f\": 76,")
        .append("\"eco_temperature_low_c\": 16.5,")
        .append("\"eco_temperature_low_f\": 62,")
        .append("\"is_locked\": false,")
        .append("\"locked_temp_min_c\": 20.0,")
        .append("\"locked_temp_min_f\": 68,")
        .append("\"locked_temp_max_c\": 22.0,")
        .append("\"locked_temp_max_f\": 72,")
        .append("\"sunlight_correction_active\": false,")
        .append("\"sunlight_correction_enabled\": true,")
        .append("\"structure_id\": \"structure-1-id\",")
        .append("\"fan_timer_active\": false,")
        .append("\"fan_timer_timeout\": \"1970-01-01T00:00:00.000Z\",")
        .append("\"fan_timer_duration\": 15,")
        .append("\"previous_hvac_mode\": \"heat\",")
        .append("\"hvac_mode\": \"eco\",")
        .append("\"time_to_target\": \"~0\",")
        .append("\"time_to_target_training\": \"ready\",")
        .append("\"where_name\": \"Living Room\",")
        .append("\"label\": \"Nest\",")
        .append("\"name_long\": \"Living Room Thermostat (Nest)\",")
        .append("\"is_online\": true,")
        .append("\"last_connection\": \"2017-06-15T13:30:58.420Z\",")
        .append("\"hvac_state\": \"off\",")
        .append("}")
        .toString()
}

fun buildStructureResponse(): String {
    val wheresList = StringBuilder("{")
        .append("\"backyard-id\": {")
        .append("\"where_id\": \"backyard-id\",")
        .append("\"name\": \"Backyard\"")
        .append("},")
        .append("\"basement-id\": {")
        .append("\"where_id\": \"basement-id\",")
        .append("\"name\": \"Basement\"")
        .append("},")
        .append("\"bedroom-id\": {")
        .append("\"where_id\": \"bedroom-id\",")
        .append("\"name\": \"Bedroom\"")
        .append("},")
        .append("\"den-id\": {")
        .append("\"where_id\": \"den-id\",")
        .append("\"name\": \"Den\"")
        .append("},")
        .append("\"dining-room-id\": {")
        .append("\"where_id\": \"dining-room-id\",")
        .append("\"name\": \"Dining Room\"")
        .append("},")
        .append("\"downstairs-id\": {")
        .append("\"where_id\": \"downstairs-id\",")
        .append("\"name\": \"Downstairs\"")
        .append("},")
        .append("\"driveway-id\": {")
        .append("\"where_id\": \"driveway-di\",")
        .append("\"name\": \"Driveway\"")
        .append("},")
        .append("\"entryway-id\": {")
        .append("\"where_id\": \"entryway-id\",")
        .append("\"name\": \"Entryway\"")
        .append("},")
        .append("\"family-room-id\": {")
        .append("\"where_id\": \"family-room-id\",")
        .append("\"name\": \"Family Room\"")
        .append("},")
        .append("\"front-yard-id\": {")
        .append("\"where_id\": \"front-yard-id\",")
        .append("\"name\": \"Front Yard\"")
        .append("},")
        .append("\"hallway-id\": {")
        .append("\"where_id\": \"hallway-id\",")
        .append("\"name\": \"Hallway\"")
        .append("},")
        .append("\"kids-room-id\": {")
        .append("\"where_id\": \"kids-room-id\",")
        .append("\"name\": \"Kids Room\"")
        .append("},")
        .append("\"kitchen-id\": {")
        .append("\"where_id\": \"kitchen-id\",")
        .append("\"name\": \"Kitchen\"")
        .append("},")
        .append("\"living-room-id\": {")
        .append("\"where_id\": \"living-room-id\",")
        .append("\"name\": \"Living Room\"")
        .append("},")
        .append("\"master-bedroom-id\": {")
        .append("\"where_id\": \"master-bedroom-id\",")
        .append("\"name\": \"Master Bedroom\"")
        .append("},")
        .append("\"office-id\": {")
        .append("\"where_id\": \"office-id\",")
        .append("\"name\": \"Office\"")
        .append("},")
        .append("\"outside-ide\": {")
        .append("\"where_id\": \"outside-ide\",")
        .append("\"name\": \"Outside\"")
        .append("},")
        .append("\"upstairs-id\": {")
        .append("\"where_id\": \"upstairs-id\",")
        .append("\"name\": \"Upstairs\"")
        .append("}")
        .append("}")

    return StringBuilder("{")
        .append("\"smoke_co_alarms\": [")
        .append("\"alarm-1-id\",")
        .append("\"alarm-2-id\"")
        .append("],")
        .append("\"name\": \"1234 Fake St\",")
        .append("\"country_code\": \"US\",")
        .append("\"postal_code\": \"80206\",")
        .append("\"time_zone\": \"America/Denver\",")
        .append("\"away\": \"away\",")
        .append("\"thermostats\": [")
        .append("\"thermostat-1-id\"")
        .append("],")
        .append("\"structure_id\": \"structure-1-id\",")
        .append("\"wheres\": $wheresList")
        .append("}")
        .toString()
}

fun buildRootResponse(
    ambientTemperature: Int = 70
): String {
    val thermostatInfo = buildThermostatResponse(ambientTemperature)
    val structureInfo = buildStructureResponse()

    return StringBuilder("{")
        .append("\"devices\": {")
        .append("\"thermostats\": {")
        .append("\"thermostat-1-id\": $thermostatInfo")
        .append("}")
        .append("},")
        .append("\"structures\" : {")
        .append("\"structure-1-id\": $structureInfo")
        .append("},")
        .append("\"metadata\": {")
        .append("\"access_token\": \"secret_access_token\",")
        .append("\"client_version\": 1")
        .append("}")
        .append("}")
        .toString()
}
